name: Fastlane Build & Upload (PRODUCTION Branch)

on:
  push:
    branches:
      - main
  pull_request:
    branches: [ main ]

jobs:
  build-and-upload:
    runs-on: ubuntu-latest

    env:
      BUILD_FLAVOR: default
      BUILD_VARIANT: release
      DRIVE_SERVICE_JSON_PATH: fastlane-drive-service.json

    defaults:
      run:
        working-directory: fastlane

    steps:
      - name: üßæ Checkout repo
        uses: actions/checkout@v4

      - name: Set up JDK 18
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '18'

      - name: Make gradlew executable
        run: chmod +x ../gradlew

      - name: üìÅ Copy secret.properties to project direcotry
        run: |
          cat <<EOF > ../secrets.default.properties
          ${{ secrets.SECRETS_PRODUCTION }}
          EOF
      
      - name: üìÅ Copy local.properties to project direcotry
        run: |
          cat <<EOF > ../local.properties
          ${{ secrets.LOCAL_PROPERTIES }}
          EOF

      - name: üìù Save Google Drive service JSON
        run: |
          cat <<EOF > $DRIVE_SERVICE_JSON_PATH
          ${{ secrets.DRIVE_SERVICE_JSON }}
          EOF

      - name: Cache Ruby gems
        uses: actions/cache@v3
        with:
          path: fastlane/vendor/bundle
          key: ${{ runner.os }}-gems-${{ hashFiles('fastlane/Gemfile.lock') }}
          restore-keys: |
            ${{ runner.os }}-gems-


      - name: üîß Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.2.8'  
          bundler-cache: true

      - name: üì¶ Install dependencies
        run: bundle install

      - name: üöÄ Run Fastlane build
        run: |
          bundle exec fastlane build_and_deploy
        env:
          BUILD_FLAVOR: ${{ env.BUILD_FLAVOR }}
          BUILD_VARIANT: ${{ env.BUILD_VARIANT }}
          DRIVE_FOLDER_ID: ${{ secrets.DRIVE_FOLDER_ID }}
          SLACK_CHANNEL: ${{ secrets.SLACK_CHANNEL }}
          SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}
          DRIVE_SERVICE_JSON: ${{ env.DRIVE_SERVICE_JSON_PATH }}
