name: Fastlane Build & Upload (Test Branch)

on:
  push:
    branches:
      - test
    pull_request:
    branches: [ test ]

jobs:
  build-and-upload:
    runs-on: ubuntu-latest

    env:
      BUILD_FLAVOR: default
      BUILD_VARIANT: debug
      DRIVE_FOLDER_ID: ${{ secrets.DRIVE_FOLDER_ID }}
      SLACK_CHANNEL: ${{ secrets.SLACK_CHANNEL }}
      SLACK_BOT_TOKEN: ${{ secrets.SLACK_TOKEN }}
      DRIVE_SERVICE_JSON_PATH: fastlane-drive-service.json

    defaults:
      run:
        working-directory: fastlane

    steps:
      - name: ðŸ§¾ Checkout repo
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Cache Ruby gems
        uses: actions/cache@v3
        with:
          path: fastlane/vendor/bundle
          key: ${{ runner.os }}-gems-${{ hashFiles('fastlane/Gemfile.lock') }}
          restore-keys: |
            ${{ runner.os }}-gems-


      - name: ðŸ”§ Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '2.7'  
          bundler-cache: true

      - name: ðŸ“¦ Install dependencies
        run: bundle install

      - name: Make gradlew executable
        run: chmod +x ../gradlew

      - name: ðŸ“ Copy secrets to build config
        run: |
          echo "${{ secrets.SECRETS_DEBUG }}" > secrets.default.properties

      - name: ðŸ“ Save Google Drive service JSON
        run: |
          echo '${{ secrets.DRIVE_SERVICE_JSON }}' > $DRIVE_SERVICE_JSON_PATH
        shell: bash

      - name: ðŸš€ Run Fastlane build
        run: |
          bundle exec fastlane build_and_deploy
        env:
          BUILD_FLAVOR: ${{ env.BUILD_FLAVOR }}
          BUILD_VARIANT: ${{ env.BUILD_VARIANT }}
          DRIVE_FOLDER_ID: ${{ secrets.DRIVE_FOLDER_ID }}
          SLACK_CHANNEL: ${{ secrets.SLACK_CHANNEL }}
          SLACK_BOT_TOKEN: ${{ secrets.SLACK_TOKEN }}
          DRIVE_SERVICE_JSON: ${{ env.DRIVE_SERVICE_JSON_PATH }}
