name: Fastlane Build & Upload (Test Branch)

on:
  push:
    branches:
      - test
  pull_request:
    branches: [ test ]

jobs:
  build-and-upload:
    runs-on: ubuntu-latest

    env:
      BUILD_FLAVOR: default
      BUILD_VARIANT: debug
      DRIVE_FOLDER_ID: ${{ secrets.DRIVE_FOLDER_ID }}
      SLACK_CHANNEL: ${{ secrets.SLACK_CHANNEL }}
      SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}
      DRIVE_SERVICE_JSON_PATH: fastlane-drive-service.json

    defaults:
      run:
        working-directory: fastlane

    steps:
      - name: ğŸ§¾ Checkout repo
        uses: actions/checkout@v4

      - name: Set up JDK 18
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '18'

      - name: Make gradlew executable
        run: chmod +x ../gradlew

      - name: ğŸ“ Copy secrets to build config
        run: |
          cat <<EOF > ../secrets.default.properties
          ${{ secrets.SECRETS_DEBUG }}
          EOF

      - name: ğŸ“ Save Google Drive service JSON
        run: |
          cat <<EOF > $DRIVE_SERVICE_JSON_PATH
          ${{ secrets.DRIVE_SERVICE_JSON }}
          EOF

      - name: Cache Ruby gems
        uses: actions/cache@v3
        with:
          path: fastlane/vendor/bundle
          key: ${{ runner.os }}-gems-${{ hashFiles('fastlane/Gemfile.lock') }}
          restore-keys: |
            ${{ runner.os }}-gems-


      - name: ğŸ”§ Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.2.8'  
          bundler-cache: true

      - name: ğŸ“¦ Install dependencies
        run: bundle install

      - name: ğŸš€ Run Fastlane build
        run: |
          bundle exec fastlane build_and_deploy
